apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-nodejs
  name: hello-nodejs
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-nodejs
  template:
    metadata:
      labels:
        app: hello-nodejs
    spec:
      containers:
      - image: qaxim/hello-nodejs:v1
        name: hello-nodejs
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "800m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-nodejs
  name: hello-nodejs
  namespace: app
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: hello-nodejs
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-nodejs
  namespace: app
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hello-nodejs
            port:
              number: 9000
        path: /
        pathType: Prefix
